### ISSUE TITLE
Ability to add custom base tile layers

### ISSUE THREAD

**Issue by chillu** [mediasuitenz/mappy#56]
We've previously submitted a PR for adding a Google base layer (#32). Turns out this isn't performant enough for the client, layers get visually out of sync when zooming or panning.

So we're going to use ESRI base maps instead (based on OpenStreetMap data). The ESRI tiles don't follow the common Google/Bing file name format, and have to be added through their own Leaflet plugin. Example: http://esri.github.io/esri-leaflet/examples/retina-basemap.html

We've previously dealt with the google special case through `wrappers/tilelayer.js`, and unconditionally including `vendor/leaflet-plugins-google.js`. I don't want to further bloat the Mappy lib by now also adding the ESRI JS lib (we'll add it to our custom build). 

I see two solutions for adding layers:

Solution 1: Allow layer definition as an expression which gets `eval()`ed, for example:

```json
{
  "domElementId": "map",
  "tileLayers": {
    "esriBase": {
      "constructor" : "L.esri.basemapLayer",
      "arguments": [
        "DarkGray",
        {"detectRetina": true}
      ],
      "attribution": "",
      "maxZoom": 18,
      "zIndex": 10
    },
    "esriLabels": {
      "constructor" : "L.esri.basemapLayer",
      "arguments": [
        "DarkGrayLabels"
      ],
      "attribution": "",
      "maxZoom": 18,
      "zIndex": 10
    }
  },
  "bounds": [
    [-43.577988,172.515934],
    [-43.461397,172.749529]
  ]
}
```

Solution 2: Allow leaving the base layer undefined, and deal with it in custom map initialisation. That'd break the `tileLayerManager.addLayer()` APi though, since it assumes a layer name only and wants to track the layer objects itself. We could change this API to optionally accept a layer object of course.

Am I on the right track? Which solution do you prefer?

**Comment by chillu** [comment]
Solution 1 turns out to be harder than expected, because we'd need to load esri-leaflet after the main leaflet JS, but before Mappy initialises the tile layers. This step happens directly when the various Mappy objects are constructed. Could we have a central `map.start()` method to kick this all off explicitly? Alternatively we could override the Mappy build process with our own Grunt logic, but I'm reluctant to further pile up customisations in this step.

After two hours of banging my head against it, I'm tending towards solution of just side-stepping Mappy on this one and adding the layer directly to Leaflet, instead of now trying to figure out how to expose tileLayerController through the main map object... In that case I would need to change Mappy to allow for empty "tileLayers" configs. Does that sound OK?

**Comment by digitalsadhu** [comment]
Ok, so if I understand you right a working solution might be to remove mappy's compulsory check for at least 1 tile layer and expose something so that you can manually add a tile layer.

I think in any case it might be smart to remove the compulsory tile layer check anyway. It's possible someone might have a use where there is no tile layer as such anyway.

I think the only hesitation from my point of view is encouraging direct access to leaflet. @markstuart and I discussed this earlier and as mappy stands now (as of this morning) a call to:

```js
var map = Mappy.create(config)
```
gets you a map object that has `map.map` which is a leaflet map instance so access to the leaflet map is provided but we think it should be more of an intermediate/last resort solution to problems. ie. We think that wherever possible we should expose leaflet apis directly on map as a kind of adapter so that if we ever wanted to support google maps or other mapping solutions under the hood, it would just be a case of wiring up to the map interface and would not affect consumers. So where leaflet has a method `tileLayer` it would nice to add a method directly to map like `map.addTileLayer()` etc.

In your case though, its a bit complicated since you need to include the esri plugin and perhaps you just have to sidestep mappy as you say and just access `map.map` directly. 

Unless we could come up with a way of wrapping up the esri plugin and only loading it as needed.

Long winded brain spew aside, probably let this all sit, disable tilelayer checking and sidestep mappy to get what you need done done.

**Comment by digitalsadhu** [comment]
@chillu P.S. Was there a reason you couldn't use a mapbox base tile layer?

**Comment by chillu** [comment]
Thanks Richard! For now, I've added the tiles directly without using esri-leaflet. AFAICT that's not directly supported, but I've figured out the format - and effectively the file names are a "public API" since they're coded into existing esri-leaflet releases. The library would add ~70kb gzipped to the page weight so is a pretty extreme measure just to get tiles anyway. Reasons for ESRI over MapBox ... political. MapBox has much nicer font rendering, anti-aliasing, retina support. Might bring it up again with the client. Have you figured out how to add retina tiles via MapBox without including their own lib? Looks like they use a [different logic](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/tile_layer.js#L67) to the built-in `detectRetina` in Leaflet.

Just FYI, here's my current config:

```json
{
  "domElementId": "map",
  "tileLayers": {
    "base-tiles": {
      "url": "http://{s}.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}.png",
      "subdomains": ["server", "services"],
      "attribution": "ESRI, OpenStreetMap",
      "maxZoom": 18,
      "zIndex": 10
    }
  },
  "bounds": [
    [-29.209970, 175.987198],
    [-52.618591, 165.883804]
  ],
  "exposeMapObject": true
}
```

So for now I'll close off this issue, I've got enough guidance now in case the need arises again for a more involved integration with esri-leaflet.
